# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\main_form_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1017, 655)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 130, 691, 281))
        font = QtGui.QFont()
        font.setFamily("B Titr")
        font.setPointSize(45)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1017, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.exit_menu = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.exit_menu.setFont(font)
        self.exit_menu.setObjectName("exit_menu")
        self.students_menu = QtWidgets.QAction(MainWindow)
        self.students_menu.setObjectName("students_menu")
        self.classes_menu = QtWidgets.QAction(MainWindow)
        self.classes_menu.setObjectName("classes_menu")
        self.subjects_menu = QtWidgets.QAction(MainWindow)
        self.subjects_menu.setObjectName("subjects_menu")
        self.enrollments_menu = QtWidgets.QAction(MainWindow)
        self.enrollments_menu.setObjectName("enrollments_menu")
        self.menu.addAction(self.exit_menu)
        self.menu_2.addAction(self.students_menu)
        self.menu_3.addAction(self.classes_menu)
        self.menu_4.addAction(self.subjects_menu)
        self.menu_5.addAction(self.enrollments_menu)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "مدیریت"))
        self.label.setText(_translate("MainWindow", "مدیریت مدرسه"))
        self.menu.setTitle(_translate("MainWindow", "فایل"))
        self.menu_2.setTitle(_translate("MainWindow", "دانش آموزان"))
        self.menu_3.setTitle(_translate("MainWindow", " کلاس ها"))
        self.menu_4.setTitle(_translate("MainWindow", "درس ها"))
        self.menu_5.setTitle(_translate("MainWindow", "ثبت نام"))
        self.exit_menu.setText(_translate("MainWindow", "خروج"))
        self.students_menu.setText(_translate("MainWindow", "مدیریت  دانش آموزان"))
        self.classes_menu.setText(_translate("MainWindow", "مدیریت کلاس ها"))
        self.subjects_menu.setText(_translate("MainWindow", "مدیریت درس ها"))
        self.enrollments_menu.setText(_translate("MainWindow", "مدیریت ثبت نام ها"))
