# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 474)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.manage_borrowers_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.manage_borrowers_pushButton.setGeometry(QtCore.QRect(90, 70, 211, 41))
        self.manage_borrowers_pushButton.setObjectName("manage_borrowers_pushButton")
        self.manage_loans_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.manage_loans_pushButton.setGeometry(QtCore.QRect(320, 70, 171, 41))
        self.manage_loans_pushButton.setObjectName("manage_loans_pushButton")
        self.reports_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.reports_pushButton.setGeometry(QtCore.QRect(510, 70, 251, 41))
        self.reports_pushButton.setObjectName("reports_pushButton")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(80, 180, 681, 241))
        self.tableView.setObjectName("tableView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionManage_Loans = QtWidgets.QAction(MainWindow)
        self.actionManage_Loans.setObjectName("actionManage_Loans")
        self.actionReports = QtWidgets.QAction(MainWindow)
        self.actionReports.setObjectName("actionReports")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.actionManage_Loans)
        self.menuFile.addAction(self.actionReports)
        self.menuFile.addAction(self.actionExit_2)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.manage_borrowers_pushButton.setText(_translate("MainWindow", "ManageBorrowers"))
        self.manage_loans_pushButton.setText(_translate("MainWindow", "ManageLoans"))
        self.reports_pushButton.setText(_translate("MainWindow", "Reports"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Manage Borrowers"))
        self.actionManage_Loans.setText(_translate("MainWindow", "Manage Loans"))
        self.actionReports.setText(_translate("MainWindow", "Reports"))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
